/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductNote = IDL.Record({
  'productName' : IDL.Text,
  'experience' : IDL.Text,
  'notes' : IDL.Text,
  'rating' : IDL.Nat,
});
export const SkinType = IDL.Variant({
  'dry' : IDL.Null,
  'combination' : IDL.Null,
  'normal' : IDL.Null,
  'oily' : IDL.Null,
  'sensitive' : IDL.Null,
});
export const IngredientSafety = IDL.Variant({
  'safe' : IDL.Null,
  'conditional' : IDL.Null,
  'harmful' : IDL.Null,
  'risky' : IDL.Null,
});
export const IngredientAnalysisResult = IDL.Record({
  'isCompatible' : IDL.Bool,
  'safetyClassification' : IngredientSafety,
  'explanation' : IDL.Text,
  'ingredientName' : IDL.Text,
  'concernWarnings' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductCompatibilityScore = IDL.Record({
  'verdict' : IDL.Variant({
    'fair' : IDL.Null,
    'good' : IDL.Null,
    'poor' : IDL.Null,
    'unsafe' : IDL.Null,
    'excellent' : IDL.Null,
  }),
  'score' : IDL.Nat,
});
export const PriceRange = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const ProductCategory = IDL.Variant({
  'sunscreen' : IDL.Null,
  'cleanser' : IDL.Null,
  'treatment' : IDL.Null,
  'serum' : IDL.Null,
  'moisturizer' : IDL.Null,
});
export const SkincareProduct = IDL.Record({
  'suitableSkinTypes' : IDL.Vec(SkinType),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'concerns' : IDL.Vec(IDL.Text),
  'priceRange' : PriceRange,
  'category' : ProductCategory,
  'brand' : IDL.Text,
  'keyIngredients' : IDL.Vec(IDL.Text),
});
export const ConcernLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'none' : IDL.Null,
  'medium' : IDL.Null,
});
export const SkinConcerns = IDL.Record({
  'aging' : ConcernLevel,
  'acne' : ConcernLevel,
  'concerns' : IDL.Vec(IDL.Text),
  'pigmentation' : ConcernLevel,
  'dryness' : ConcernLevel,
});
export const HighlightedIngredient = IDL.Record({
  'name' : IDL.Text,
  'reason' : IDL.Text,
  'classification' : IngredientSafety,
});
export const ExplanatoryPanel = IDL.Record({
  'highlightedIngredients' : IDL.Vec(HighlightedIngredient),
  'suggestedAlternatives' : IDL.Vec(IDL.Text),
  'scientificReasoning' : IDL.Text,
});
export const ProductSuitability = IDL.Variant({
  'caution' : IDL.Null,
  'suitable' : IDL.Null,
  'not_recommended' : IDL.Null,
});
export const SuitabilityResult = IDL.Record({
  'explanation' : ExplanatoryPanel,
  'suitability' : ProductSuitability,
});
export const IngredientInfo = IDL.Record({
  'suitableSkinTypes' : IDL.Vec(SkinType),
  'isAcneProneConcern' : IDL.Bool,
  'isClogProneConcern' : IDL.Bool,
  'safetyClassification' : IngredientSafety,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isSensitiveConcern' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ProgressMetrics = IDL.Record({
  'stableSkinType' : IDL.Nat,
  'drynessTrend' : IDL.Text,
  'pigmentationTrend' : IDL.Text,
  'agingTrend' : IDL.Text,
  'acneTrend' : IDL.Text,
});
export const RoutineStep = IDL.Record({
  'order' : IDL.Nat,
  'productName' : IDL.Text,
  'frequency' : IDL.Nat,
});
export const SkincareRoutine = IDL.Record({
  'name' : IDL.Text,
  'steps' : IDL.Vec(RoutineStep),
});
export const SkinTypeData = IDL.Record({
  'answers' : IDL.Vec(IDL.Nat),
  'concerns' : SkinConcerns,
  'timestamp' : IDL.Nat,
  'detectedSkinType' : SkinType,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFavorite' : IDL.Func([IDL.Text], [], []),
  'addProductNote' : IDL.Func([ProductNote], [], []),
  'analyzeIngredients' : IDL.Func(
      [IDL.Vec(IDL.Text), SkinType],
      [IDL.Vec(IngredientAnalysisResult)],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateProductCompatibilityScore' : IDL.Func(
      [IDL.Vec(IngredientAnalysisResult)],
      [ProductCompatibilityScore],
      ['query'],
    ),
  'clearStore' : IDL.Func([], [], []),
  'compareProducts' : IDL.Func(
      [IDL.Vec(IDL.Text), SkinType],
      [
        IDL.Record({
          'products' : IDL.Vec(SkincareProduct),
          'analysis' : IDL.Vec(IngredientAnalysisResult),
        }),
      ],
      [],
    ),
  'confirmSkinType' : IDL.Func([SkinType, SkinConcerns], [], []),
  'deleteByTimeStamp' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'deleteRoutine' : IDL.Func([IDL.Text], [], []),
  'deleteUserData' : IDL.Func([IDL.Principal], [], []),
  'evaluateProductSuitability' : IDL.Func(
      [IDL.Text, SkinType, SkinConcerns],
      [SuitabilityResult],
      ['query'],
    ),
  'getAllIngredients' : IDL.Func([], [IDL.Vec(IngredientInfo)], ['query']),
  'getAllProductNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getIngredient' : IDL.Func([IDL.Text], [IDL.Opt(IngredientInfo)], ['query']),
  'getLatestSkinType' : IDL.Func([], [IDL.Opt(SkinType)], ['query']),
  'getMyRecordCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPersonalizedRecommendations' : IDL.Func(
      [SkinType, SkinConcerns],
      [IDL.Vec(SkincareProduct)],
      ['query'],
    ),
  'getProductNotes' : IDL.Func([], [IDL.Vec(ProductNote)], ['query']),
  'getProgressMetrics' : IDL.Func([], [ProgressMetrics], ['query']),
  'getRoutines' : IDL.Func([], [IDL.Vec(SkincareRoutine)], ['query']),
  'getSkinTypeDataByTimestamp' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(SkinTypeData)],
      ['query'],
    ),
  'getSkinTypeDetectionResults' : IDL.Func(
      [],
      [IDL.Vec(SkinTypeData)],
      ['query'],
    ),
  'getStoreCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFavorite' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProduct' : IDL.Func([SkincareProduct], [], []),
  'saveRoutine' : IDL.Func([SkincareRoutine], [], []),
  'saveSkinTypeData' : IDL.Func([SkinTypeData], [], []),
  'searchProductByName' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SkincareProduct)],
      ['query'],
    ),
  'seedIngredients' : IDL.Func([], [], []),
  'setSkincareProducts' : IDL.Func([IDL.Vec(SkincareProduct)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductNote = IDL.Record({
    'productName' : IDL.Text,
    'experience' : IDL.Text,
    'notes' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const SkinType = IDL.Variant({
    'dry' : IDL.Null,
    'combination' : IDL.Null,
    'normal' : IDL.Null,
    'oily' : IDL.Null,
    'sensitive' : IDL.Null,
  });
  const IngredientSafety = IDL.Variant({
    'safe' : IDL.Null,
    'conditional' : IDL.Null,
    'harmful' : IDL.Null,
    'risky' : IDL.Null,
  });
  const IngredientAnalysisResult = IDL.Record({
    'isCompatible' : IDL.Bool,
    'safetyClassification' : IngredientSafety,
    'explanation' : IDL.Text,
    'ingredientName' : IDL.Text,
    'concernWarnings' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductCompatibilityScore = IDL.Record({
    'verdict' : IDL.Variant({
      'fair' : IDL.Null,
      'good' : IDL.Null,
      'poor' : IDL.Null,
      'unsafe' : IDL.Null,
      'excellent' : IDL.Null,
    }),
    'score' : IDL.Nat,
  });
  const PriceRange = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const ProductCategory = IDL.Variant({
    'sunscreen' : IDL.Null,
    'cleanser' : IDL.Null,
    'treatment' : IDL.Null,
    'serum' : IDL.Null,
    'moisturizer' : IDL.Null,
  });
  const SkincareProduct = IDL.Record({
    'suitableSkinTypes' : IDL.Vec(SkinType),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'concerns' : IDL.Vec(IDL.Text),
    'priceRange' : PriceRange,
    'category' : ProductCategory,
    'brand' : IDL.Text,
    'keyIngredients' : IDL.Vec(IDL.Text),
  });
  const ConcernLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'none' : IDL.Null,
    'medium' : IDL.Null,
  });
  const SkinConcerns = IDL.Record({
    'aging' : ConcernLevel,
    'acne' : ConcernLevel,
    'concerns' : IDL.Vec(IDL.Text),
    'pigmentation' : ConcernLevel,
    'dryness' : ConcernLevel,
  });
  const HighlightedIngredient = IDL.Record({
    'name' : IDL.Text,
    'reason' : IDL.Text,
    'classification' : IngredientSafety,
  });
  const ExplanatoryPanel = IDL.Record({
    'highlightedIngredients' : IDL.Vec(HighlightedIngredient),
    'suggestedAlternatives' : IDL.Vec(IDL.Text),
    'scientificReasoning' : IDL.Text,
  });
  const ProductSuitability = IDL.Variant({
    'caution' : IDL.Null,
    'suitable' : IDL.Null,
    'not_recommended' : IDL.Null,
  });
  const SuitabilityResult = IDL.Record({
    'explanation' : ExplanatoryPanel,
    'suitability' : ProductSuitability,
  });
  const IngredientInfo = IDL.Record({
    'suitableSkinTypes' : IDL.Vec(SkinType),
    'isAcneProneConcern' : IDL.Bool,
    'isClogProneConcern' : IDL.Bool,
    'safetyClassification' : IngredientSafety,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isSensitiveConcern' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ProgressMetrics = IDL.Record({
    'stableSkinType' : IDL.Nat,
    'drynessTrend' : IDL.Text,
    'pigmentationTrend' : IDL.Text,
    'agingTrend' : IDL.Text,
    'acneTrend' : IDL.Text,
  });
  const RoutineStep = IDL.Record({
    'order' : IDL.Nat,
    'productName' : IDL.Text,
    'frequency' : IDL.Nat,
  });
  const SkincareRoutine = IDL.Record({
    'name' : IDL.Text,
    'steps' : IDL.Vec(RoutineStep),
  });
  const SkinTypeData = IDL.Record({
    'answers' : IDL.Vec(IDL.Nat),
    'concerns' : SkinConcerns,
    'timestamp' : IDL.Nat,
    'detectedSkinType' : SkinType,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFavorite' : IDL.Func([IDL.Text], [], []),
    'addProductNote' : IDL.Func([ProductNote], [], []),
    'analyzeIngredients' : IDL.Func(
        [IDL.Vec(IDL.Text), SkinType],
        [IDL.Vec(IngredientAnalysisResult)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateProductCompatibilityScore' : IDL.Func(
        [IDL.Vec(IngredientAnalysisResult)],
        [ProductCompatibilityScore],
        ['query'],
      ),
    'clearStore' : IDL.Func([], [], []),
    'compareProducts' : IDL.Func(
        [IDL.Vec(IDL.Text), SkinType],
        [
          IDL.Record({
            'products' : IDL.Vec(SkincareProduct),
            'analysis' : IDL.Vec(IngredientAnalysisResult),
          }),
        ],
        [],
      ),
    'confirmSkinType' : IDL.Func([SkinType, SkinConcerns], [], []),
    'deleteByTimeStamp' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'deleteRoutine' : IDL.Func([IDL.Text], [], []),
    'deleteUserData' : IDL.Func([IDL.Principal], [], []),
    'evaluateProductSuitability' : IDL.Func(
        [IDL.Text, SkinType, SkinConcerns],
        [SuitabilityResult],
        ['query'],
      ),
    'getAllIngredients' : IDL.Func([], [IDL.Vec(IngredientInfo)], ['query']),
    'getAllProductNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getIngredient' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IngredientInfo)],
        ['query'],
      ),
    'getLatestSkinType' : IDL.Func([], [IDL.Opt(SkinType)], ['query']),
    'getMyRecordCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPersonalizedRecommendations' : IDL.Func(
        [SkinType, SkinConcerns],
        [IDL.Vec(SkincareProduct)],
        ['query'],
      ),
    'getProductNotes' : IDL.Func([], [IDL.Vec(ProductNote)], ['query']),
    'getProgressMetrics' : IDL.Func([], [ProgressMetrics], ['query']),
    'getRoutines' : IDL.Func([], [IDL.Vec(SkincareRoutine)], ['query']),
    'getSkinTypeDataByTimestamp' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SkinTypeData)],
        ['query'],
      ),
    'getSkinTypeDetectionResults' : IDL.Func(
        [],
        [IDL.Vec(SkinTypeData)],
        ['query'],
      ),
    'getStoreCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFavorite' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProduct' : IDL.Func([SkincareProduct], [], []),
    'saveRoutine' : IDL.Func([SkincareRoutine], [], []),
    'saveSkinTypeData' : IDL.Func([SkinTypeData], [], []),
    'searchProductByName' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SkincareProduct)],
        ['query'],
      ),
    'seedIngredients' : IDL.Func([], [], []),
    'setSkincareProducts' : IDL.Func([IDL.Vec(SkincareProduct)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };