/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ConcernLevel = { 'low' : null } |
  { 'high' : null } |
  { 'none' : null } |
  { 'medium' : null };
export interface ExplanatoryPanel {
  'highlightedIngredients' : Array<HighlightedIngredient>,
  'suggestedAlternatives' : Array<string>,
  'scientificReasoning' : string,
}
export interface HighlightedIngredient {
  'name' : string,
  'reason' : string,
  'classification' : IngredientSafety,
}
export interface IngredientAnalysisResult {
  'isCompatible' : boolean,
  'safetyClassification' : IngredientSafety,
  'explanation' : string,
  'ingredientName' : string,
  'concernWarnings' : boolean,
}
export interface IngredientInfo {
  'suitableSkinTypes' : Array<SkinType>,
  'isAcneProneConcern' : boolean,
  'isClogProneConcern' : boolean,
  'safetyClassification' : IngredientSafety,
  'name' : string,
  'description' : string,
  'isSensitiveConcern' : boolean,
}
export type IngredientSafety = { 'safe' : null } |
  { 'conditional' : null } |
  { 'harmful' : null } |
  { 'risky' : null };
export type PriceRange = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type ProductCategory = { 'sunscreen' : null } |
  { 'cleanser' : null } |
  { 'treatment' : null } |
  { 'serum' : null } |
  { 'moisturizer' : null };
export interface ProductCompatibilityScore {
  'verdict' : { 'fair' : null } |
    { 'good' : null } |
    { 'poor' : null } |
    { 'unsafe' : null } |
    { 'excellent' : null },
  'score' : bigint,
}
export interface ProductNote {
  'productName' : string,
  'experience' : string,
  'notes' : string,
  'rating' : bigint,
}
export type ProductSuitability = { 'caution' : null } |
  { 'suitable' : null } |
  { 'not_recommended' : null };
export interface ProgressMetrics {
  'stableSkinType' : bigint,
  'drynessTrend' : string,
  'pigmentationTrend' : string,
  'agingTrend' : string,
  'acneTrend' : string,
}
export interface RoutineStep {
  'order' : bigint,
  'productName' : string,
  'frequency' : bigint,
}
export interface SkinConcerns {
  'aging' : ConcernLevel,
  'acne' : ConcernLevel,
  'concerns' : Array<string>,
  'pigmentation' : ConcernLevel,
  'dryness' : ConcernLevel,
}
export type SkinType = { 'dry' : null } |
  { 'combination' : null } |
  { 'normal' : null } |
  { 'oily' : null } |
  { 'sensitive' : null };
export interface SkinTypeData {
  'answers' : Array<bigint>,
  'concerns' : SkinConcerns,
  'timestamp' : bigint,
  'detectedSkinType' : SkinType,
}
export interface SkincareProduct {
  'suitableSkinTypes' : Array<SkinType>,
  'name' : string,
  'description' : string,
  'concerns' : Array<string>,
  'priceRange' : PriceRange,
  'category' : ProductCategory,
  'brand' : string,
  'keyIngredients' : Array<string>,
}
export interface SkincareRoutine {
  'name' : string,
  'steps' : Array<RoutineStep>,
}
export interface SuitabilityResult {
  'explanation' : ExplanatoryPanel,
  'suitability' : ProductSuitability,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFavorite' : ActorMethod<[string], undefined>,
  'addProductNote' : ActorMethod<[ProductNote], undefined>,
  'analyzeIngredients' : ActorMethod<
    [Array<string>, SkinType],
    Array<IngredientAnalysisResult>
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateProductCompatibilityScore' : ActorMethod<
    [Array<IngredientAnalysisResult>],
    ProductCompatibilityScore
  >,
  'clearStore' : ActorMethod<[], undefined>,
  'compareProducts' : ActorMethod<
    [Array<string>, SkinType],
    {
      'products' : Array<SkincareProduct>,
      'analysis' : Array<IngredientAnalysisResult>,
    }
  >,
  'confirmSkinType' : ActorMethod<[SkinType, SkinConcerns], undefined>,
  'deleteByTimeStamp' : ActorMethod<[Principal, bigint], undefined>,
  'deleteRoutine' : ActorMethod<[string], undefined>,
  'deleteUserData' : ActorMethod<[Principal], undefined>,
  'evaluateProductSuitability' : ActorMethod<
    [string, SkinType, SkinConcerns],
    SuitabilityResult
  >,
  'getAllIngredients' : ActorMethod<[], Array<IngredientInfo>>,
  'getAllProductNames' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavorites' : ActorMethod<[], Array<string>>,
  'getIngredient' : ActorMethod<[string], [] | [IngredientInfo]>,
  'getLatestSkinType' : ActorMethod<[], [] | [SkinType]>,
  'getMyRecordCount' : ActorMethod<[], bigint>,
  'getPersonalizedRecommendations' : ActorMethod<
    [SkinType, SkinConcerns],
    Array<SkincareProduct>
  >,
  'getProductNotes' : ActorMethod<[], Array<ProductNote>>,
  'getProgressMetrics' : ActorMethod<[], ProgressMetrics>,
  'getRoutines' : ActorMethod<[], Array<SkincareRoutine>>,
  'getSkinTypeDataByTimestamp' : ActorMethod<[bigint], [] | [SkinTypeData]>,
  'getSkinTypeDetectionResults' : ActorMethod<[], Array<SkinTypeData>>,
  'getStoreCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFavorite' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProduct' : ActorMethod<[SkincareProduct], undefined>,
  'saveRoutine' : ActorMethod<[SkincareRoutine], undefined>,
  'saveSkinTypeData' : ActorMethod<[SkinTypeData], undefined>,
  'searchProductByName' : ActorMethod<[string], [] | [SkincareProduct]>,
  'seedIngredients' : ActorMethod<[], undefined>,
  'setSkincareProducts' : ActorMethod<[Array<SkincareProduct>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];