/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface IngredientInfo {
    suitableSkinTypes: Array<SkinType>;
    isAcneProneConcern: boolean;
    isClogProneConcern: boolean;
    safetyClassification: IngredientSafety;
    name: string;
    description: string;
    isSensitiveConcern: boolean;
}
export interface HighlightedIngredient {
    name: string;
    reason: string;
    classification: IngredientSafety;
}
export interface ExplanatoryPanel {
    highlightedIngredients: Array<HighlightedIngredient>;
    suggestedAlternatives: Array<string>;
    scientificReasoning: string;
}
export interface SkincareRoutine {
    name: string;
    steps: Array<RoutineStep>;
}
export interface SkincareProduct {
    suitableSkinTypes: Array<SkinType>;
    name: string;
    description: string;
    concerns: Array<string>;
    priceRange: PriceRange;
    category: ProductCategory;
    brand: string;
    keyIngredients: Array<string>;
}
export interface RoutineStep {
    order: bigint;
    productName: string;
    frequency: bigint;
}
export interface ProgressMetrics {
    stableSkinType: bigint;
    drynessTrend: string;
    pigmentationTrend: string;
    agingTrend: string;
    acneTrend: string;
}
export interface ProductNote {
    productName: string;
    experience: string;
    notes: string;
    rating: bigint;
}
export interface SuitabilityResult {
    explanation: ExplanatoryPanel;
    suitability: ProductSuitability;
}
export interface IngredientAnalysisResult {
    isCompatible: boolean;
    safetyClassification: IngredientSafety;
    explanation: string;
    ingredientName: string;
    concernWarnings: boolean;
}
export interface SkinTypeData {
    answers: Array<bigint>;
    concerns: SkinConcerns;
    timestamp: bigint;
    detectedSkinType: SkinType;
}
export interface SkinConcerns {
    aging: ConcernLevel;
    acne: ConcernLevel;
    concerns: Array<string>;
    pigmentation: ConcernLevel;
    dryness: ConcernLevel;
}
export interface ProductCompatibilityScore {
    verdict: Variant_fair_good_poor_unsafe_excellent;
    score: bigint;
}
export interface UserProfile {
    name: string;
}
export enum ConcernLevel {
    low = "low",
    high = "high",
    none = "none",
    medium = "medium"
}
export enum IngredientSafety {
    safe = "safe",
    conditional = "conditional",
    harmful = "harmful",
    risky = "risky"
}
export enum PriceRange {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum ProductCategory {
    sunscreen = "sunscreen",
    cleanser = "cleanser",
    treatment = "treatment",
    serum = "serum",
    moisturizer = "moisturizer"
}
export enum ProductSuitability {
    caution = "caution",
    suitable = "suitable",
    not_recommended = "not_recommended"
}
export enum SkinType {
    dry = "dry",
    combination = "combination",
    normal = "normal",
    oily = "oily",
    sensitive = "sensitive"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_fair_good_poor_unsafe_excellent {
    fair = "fair",
    good = "good",
    poor = "poor",
    unsafe = "unsafe",
    excellent = "excellent"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addFavorite(productName: string): Promise<void>;
    addProductNote(note: ProductNote): Promise<void>;
    analyzeIngredients(ingredientNames: Array<string>, userSkinType: SkinType): Promise<Array<IngredientAnalysisResult>>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateProductCompatibilityScore(results: Array<IngredientAnalysisResult>): Promise<ProductCompatibilityScore>;
    clearStore(): Promise<void>;
    compareProducts(productNames: Array<string>, userSkinType: SkinType): Promise<{
        products: Array<SkincareProduct>;
        analysis: Array<IngredientAnalysisResult>;
    }>;
    confirmSkinType(skinType: SkinType, concerns: SkinConcerns): Promise<void>;
    deleteByTimeStamp(user: Principal, timestamp: bigint): Promise<void>;
    deleteRoutine(routineName: string): Promise<void>;
    deleteUserData(user: Principal): Promise<void>;
    evaluateProductSuitability(productName: string, userSkinType: SkinType, arg2: SkinConcerns): Promise<SuitabilityResult>;
    getAllIngredients(): Promise<Array<IngredientInfo>>;
    getAllProductNames(): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFavorites(): Promise<Array<string>>;
    getIngredient(name: string): Promise<IngredientInfo | null>;
    getLatestSkinType(): Promise<SkinType | null>;
    getMyRecordCount(): Promise<bigint>;
    getPersonalizedRecommendations(userSkinType: SkinType, concerns: SkinConcerns): Promise<Array<SkincareProduct>>;
    getProductNotes(): Promise<Array<ProductNote>>;
    getProgressMetrics(): Promise<ProgressMetrics>;
    getRoutines(): Promise<Array<SkincareRoutine>>;
    getSkinTypeDataByTimestamp(timestamp: bigint): Promise<SkinTypeData | null>;
    getSkinTypeDetectionResults(): Promise<Array<SkinTypeData>>;
    getStoreCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeFavorite(productName: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveProduct(product: SkincareProduct): Promise<void>;
    saveRoutine(routine: SkincareRoutine): Promise<void>;
    saveSkinTypeData(skinTypeData: SkinTypeData): Promise<void>;
    searchProductByName(productName: string): Promise<SkincareProduct | null>;
    seedIngredients(): Promise<void>;
    setSkincareProducts(products: Array<SkincareProduct>): Promise<void>;
}
import type { ConcernLevel as _ConcernLevel, ExplanatoryPanel as _ExplanatoryPanel, HighlightedIngredient as _HighlightedIngredient, IngredientAnalysisResult as _IngredientAnalysisResult, IngredientInfo as _IngredientInfo, IngredientSafety as _IngredientSafety, PriceRange as _PriceRange, ProductCategory as _ProductCategory, ProductCompatibilityScore as _ProductCompatibilityScore, ProductSuitability as _ProductSuitability, SkinConcerns as _SkinConcerns, SkinType as _SkinType, SkinTypeData as _SkinTypeData, SkincareProduct as _SkincareProduct, SuitabilityResult as _SuitabilityResult, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addFavorite(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavorite(arg0);
            return result;
        }
    }
    async addProductNote(arg0: ProductNote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProductNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProductNote(arg0);
            return result;
        }
    }
    async analyzeIngredients(arg0: Array<string>, arg1: SkinType): Promise<Array<IngredientAnalysisResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeIngredients(arg0, to_candid_SkinType_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeIngredients(arg0, to_candid_SkinType_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateProductCompatibilityScore(arg0: Array<IngredientAnalysisResult>): Promise<ProductCompatibilityScore> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateProductCompatibilityScore(to_candid_vec_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ProductCompatibilityScore_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateProductCompatibilityScore(to_candid_vec_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ProductCompatibilityScore_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearStore(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearStore();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearStore();
            return result;
        }
    }
    async compareProducts(arg0: Array<string>, arg1: SkinType): Promise<{
        products: Array<SkincareProduct>;
        analysis: Array<IngredientAnalysisResult>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.compareProducts(arg0, to_candid_SkinType_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_record_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.compareProducts(arg0, to_candid_SkinType_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_record_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async confirmSkinType(arg0: SkinType, arg1: SkinConcerns): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmSkinType(to_candid_SkinType_n1(this._uploadFile, this._downloadFile, arg0), to_candid_SkinConcerns_n29(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmSkinType(to_candid_SkinType_n1(this._uploadFile, this._downloadFile, arg0), to_candid_SkinConcerns_n29(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteByTimeStamp(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteByTimeStamp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteByTimeStamp(arg0, arg1);
            return result;
        }
    }
    async deleteRoutine(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRoutine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRoutine(arg0);
            return result;
        }
    }
    async deleteUserData(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUserData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUserData(arg0);
            return result;
        }
    }
    async evaluateProductSuitability(arg0: string, arg1: SkinType, arg2: SkinConcerns): Promise<SuitabilityResult> {
        if (this.processError) {
            try {
                const result = await this.actor.evaluateProductSuitability(arg0, to_candid_SkinType_n1(this._uploadFile, this._downloadFile, arg1), to_candid_SkinConcerns_n29(this._uploadFile, this._downloadFile, arg2));
                return from_candid_SuitabilityResult_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.evaluateProductSuitability(arg0, to_candid_SkinType_n1(this._uploadFile, this._downloadFile, arg1), to_candid_SkinConcerns_n29(this._uploadFile, this._downloadFile, arg2));
            return from_candid_SuitabilityResult_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllIngredients(): Promise<Array<IngredientInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIngredients();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIngredients();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProductNames(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProductNames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProductNames();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFavorites(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavorites();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavorites();
            return result;
        }
    }
    async getIngredient(arg0: string): Promise<IngredientInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIngredient(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIngredient(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestSkinType(): Promise<SkinType | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestSkinType();
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestSkinType();
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRecordCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRecordCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRecordCount();
            return result;
        }
    }
    async getPersonalizedRecommendations(arg0: SkinType, arg1: SkinConcerns): Promise<Array<SkincareProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersonalizedRecommendations(to_candid_SkinType_n1(this._uploadFile, this._downloadFile, arg0), to_candid_SkinConcerns_n29(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersonalizedRecommendations(to_candid_SkinType_n1(this._uploadFile, this._downloadFile, arg0), to_candid_SkinConcerns_n29(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductNotes(): Promise<Array<ProductNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductNotes();
            return result;
        }
    }
    async getProgressMetrics(): Promise<ProgressMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgressMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgressMetrics();
            return result;
        }
    }
    async getRoutines(): Promise<Array<SkincareRoutine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoutines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoutines();
            return result;
        }
    }
    async getSkinTypeDataByTimestamp(arg0: bigint): Promise<SkinTypeData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkinTypeDataByTimestamp(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkinTypeDataByTimestamp(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSkinTypeDetectionResults(): Promise<Array<SkinTypeData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkinTypeDetectionResults();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkinTypeDetectionResults();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoreCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoreCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoreCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeFavorite(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavorite(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveProduct(arg0: SkincareProduct): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProduct(to_candid_SkincareProduct_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProduct(to_candid_SkincareProduct_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveRoutine(arg0: SkincareRoutine): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveRoutine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveRoutine(arg0);
            return result;
        }
    }
    async saveSkinTypeData(arg0: SkinTypeData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSkinTypeData(to_candid_SkinTypeData_n65(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSkinTypeData(to_candid_SkinTypeData_n65(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchProductByName(arg0: string): Promise<SkincareProduct | null> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProductByName(arg0);
                return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProductByName(arg0);
            return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedIngredients(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedIngredients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedIngredients();
            return result;
        }
    }
    async setSkincareProducts(arg0: Array<SkincareProduct>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSkincareProducts(to_candid_vec_n68(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSkincareProducts(to_candid_vec_n68(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_ConcernLevel_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConcernLevel): ConcernLevel {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_ExplanatoryPanel_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExplanatoryPanel): ExplanatoryPanel {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_HighlightedIngredient_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HighlightedIngredient): HighlightedIngredient {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_IngredientAnalysisResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IngredientAnalysisResult): IngredientAnalysisResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_IngredientInfo_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IngredientInfo): IngredientInfo {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_IngredientSafety_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IngredientSafety): IngredientSafety {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PriceRange_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceRange): PriceRange {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCompatibilityScore_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCompatibilityScore): ProductCompatibilityScore {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ProductSuitability_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductSuitability): ProductSuitability {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_SkinConcerns_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkinConcerns): SkinConcerns {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_SkinTypeData_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkinTypeData): SkinTypeData {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_SkinType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkinType): SkinType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_SkincareProduct_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkincareProduct): SkincareProduct {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_SuitabilityResult_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SuitabilityResult): SuitabilityResult {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IngredientInfo]): IngredientInfo | null {
    return value.length === 0 ? null : from_candid_IngredientInfo_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SkinType]): SkinType | null {
    return value.length === 0 ? null : from_candid_SkinType_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SkinTypeData]): SkinTypeData | null {
    return value.length === 0 ? null : from_candid_SkinTypeData_n51(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SkincareProduct]): SkincareProduct | null {
    return value.length === 0 ? null : from_candid_SkincareProduct_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verdict: {
        fair: null;
    } | {
        good: null;
    } | {
        poor: null;
    } | {
        unsafe: null;
    } | {
        excellent: null;
    };
    score: bigint;
}): {
    verdict: Variant_fair_good_poor_unsafe_excellent;
    score: bigint;
} {
    return {
        verdict: from_candid_variant_n17(_uploadFile, _downloadFile, value.verdict),
        score: value.score
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    products: Array<_SkincareProduct>;
    analysis: Array<_IngredientAnalysisResult>;
}): {
    products: Array<SkincareProduct>;
    analysis: Array<IngredientAnalysisResult>;
} {
    return {
        products: from_candid_vec_n19(_uploadFile, _downloadFile, value.products),
        analysis: from_candid_vec_n3(_uploadFile, _downloadFile, value.analysis)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    suitableSkinTypes: Array<_SkinType>;
    name: string;
    description: string;
    concerns: Array<string>;
    priceRange: _PriceRange;
    category: _ProductCategory;
    brand: string;
    keyIngredients: Array<string>;
}): {
    suitableSkinTypes: Array<SkinType>;
    name: string;
    description: string;
    concerns: Array<string>;
    priceRange: PriceRange;
    category: ProductCategory;
    brand: string;
    keyIngredients: Array<string>;
} {
    return {
        suitableSkinTypes: from_candid_vec_n22(_uploadFile, _downloadFile, value.suitableSkinTypes),
        name: value.name,
        description: value.description,
        concerns: value.concerns,
        priceRange: from_candid_PriceRange_n25(_uploadFile, _downloadFile, value.priceRange),
        category: from_candid_ProductCategory_n27(_uploadFile, _downloadFile, value.category),
        brand: value.brand,
        keyIngredients: value.keyIngredients
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    explanation: _ExplanatoryPanel;
    suitability: _ProductSuitability;
}): {
    explanation: ExplanatoryPanel;
    suitability: ProductSuitability;
} {
    return {
        explanation: from_candid_ExplanatoryPanel_n35(_uploadFile, _downloadFile, value.explanation),
        suitability: from_candid_ProductSuitability_n40(_uploadFile, _downloadFile, value.suitability)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    highlightedIngredients: Array<_HighlightedIngredient>;
    suggestedAlternatives: Array<string>;
    scientificReasoning: string;
}): {
    highlightedIngredients: Array<HighlightedIngredient>;
    suggestedAlternatives: Array<string>;
    scientificReasoning: string;
} {
    return {
        highlightedIngredients: from_candid_vec_n37(_uploadFile, _downloadFile, value.highlightedIngredients),
        suggestedAlternatives: value.suggestedAlternatives,
        scientificReasoning: value.scientificReasoning
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    reason: string;
    classification: _IngredientSafety;
}): {
    name: string;
    reason: string;
    classification: IngredientSafety;
} {
    return {
        name: value.name,
        reason: value.reason,
        classification: from_candid_IngredientSafety_n6(_uploadFile, _downloadFile, value.classification)
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    suitableSkinTypes: Array<_SkinType>;
    isAcneProneConcern: boolean;
    isClogProneConcern: boolean;
    safetyClassification: _IngredientSafety;
    name: string;
    description: string;
    isSensitiveConcern: boolean;
}): {
    suitableSkinTypes: Array<SkinType>;
    isAcneProneConcern: boolean;
    isClogProneConcern: boolean;
    safetyClassification: IngredientSafety;
    name: string;
    description: string;
    isSensitiveConcern: boolean;
} {
    return {
        suitableSkinTypes: from_candid_vec_n22(_uploadFile, _downloadFile, value.suitableSkinTypes),
        isAcneProneConcern: value.isAcneProneConcern,
        isClogProneConcern: value.isClogProneConcern,
        safetyClassification: from_candid_IngredientSafety_n6(_uploadFile, _downloadFile, value.safetyClassification),
        name: value.name,
        description: value.description,
        isSensitiveConcern: value.isSensitiveConcern
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isCompatible: boolean;
    safetyClassification: _IngredientSafety;
    explanation: string;
    ingredientName: string;
    concernWarnings: boolean;
}): {
    isCompatible: boolean;
    safetyClassification: IngredientSafety;
    explanation: string;
    ingredientName: string;
    concernWarnings: boolean;
} {
    return {
        isCompatible: value.isCompatible,
        safetyClassification: from_candid_IngredientSafety_n6(_uploadFile, _downloadFile, value.safetyClassification),
        explanation: value.explanation,
        ingredientName: value.ingredientName,
        concernWarnings: value.concernWarnings
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    answers: Array<bigint>;
    concerns: _SkinConcerns;
    timestamp: bigint;
    detectedSkinType: _SkinType;
}): {
    answers: Array<bigint>;
    concerns: SkinConcerns;
    timestamp: bigint;
    detectedSkinType: SkinType;
} {
    return {
        answers: value.answers,
        concerns: from_candid_SkinConcerns_n53(_uploadFile, _downloadFile, value.concerns),
        timestamp: value.timestamp,
        detectedSkinType: from_candid_SkinType_n23(_uploadFile, _downloadFile, value.detectedSkinType)
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aging: _ConcernLevel;
    acne: _ConcernLevel;
    concerns: Array<string>;
    pigmentation: _ConcernLevel;
    dryness: _ConcernLevel;
}): {
    aging: ConcernLevel;
    acne: ConcernLevel;
    concerns: Array<string>;
    pigmentation: ConcernLevel;
    dryness: ConcernLevel;
} {
    return {
        aging: from_candid_ConcernLevel_n55(_uploadFile, _downloadFile, value.aging),
        acne: from_candid_ConcernLevel_n55(_uploadFile, _downloadFile, value.acne),
        concerns: value.concerns,
        pigmentation: from_candid_ConcernLevel_n55(_uploadFile, _downloadFile, value.pigmentation),
        dryness: from_candid_ConcernLevel_n55(_uploadFile, _downloadFile, value.dryness)
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fair: null;
} | {
    good: null;
} | {
    poor: null;
} | {
    unsafe: null;
} | {
    excellent: null;
}): Variant_fair_good_poor_unsafe_excellent {
    return "fair" in value ? Variant_fair_good_poor_unsafe_excellent.fair : "good" in value ? Variant_fair_good_poor_unsafe_excellent.good : "poor" in value ? Variant_fair_good_poor_unsafe_excellent.poor : "unsafe" in value ? Variant_fair_good_poor_unsafe_excellent.unsafe : "excellent" in value ? Variant_fair_good_poor_unsafe_excellent.excellent : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dry: null;
} | {
    combination: null;
} | {
    normal: null;
} | {
    oily: null;
} | {
    sensitive: null;
}): SkinType {
    return "dry" in value ? SkinType.dry : "combination" in value ? SkinType.combination : "normal" in value ? SkinType.normal : "oily" in value ? SkinType.oily : "sensitive" in value ? SkinType.sensitive : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): PriceRange {
    return "low" in value ? PriceRange.low : "high" in value ? PriceRange.high : "medium" in value ? PriceRange.medium : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sunscreen: null;
} | {
    cleanser: null;
} | {
    treatment: null;
} | {
    serum: null;
} | {
    moisturizer: null;
}): ProductCategory {
    return "sunscreen" in value ? ProductCategory.sunscreen : "cleanser" in value ? ProductCategory.cleanser : "treatment" in value ? ProductCategory.treatment : "serum" in value ? ProductCategory.serum : "moisturizer" in value ? ProductCategory.moisturizer : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    caution: null;
} | {
    suitable: null;
} | {
    not_recommended: null;
}): ProductSuitability {
    return "caution" in value ? ProductSuitability.caution : "suitable" in value ? ProductSuitability.suitable : "not_recommended" in value ? ProductSuitability.not_recommended : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    none: null;
} | {
    medium: null;
}): ConcernLevel {
    return "low" in value ? ConcernLevel.low : "high" in value ? ConcernLevel.high : "none" in value ? ConcernLevel.none : "medium" in value ? ConcernLevel.medium : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    safe: null;
} | {
    conditional: null;
} | {
    harmful: null;
} | {
    risky: null;
}): IngredientSafety {
    return "safe" in value ? IngredientSafety.safe : "conditional" in value ? IngredientSafety.conditional : "harmful" in value ? IngredientSafety.harmful : "risky" in value ? IngredientSafety.risky : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SkincareProduct>): Array<SkincareProduct> {
    return value.map((x)=>from_candid_SkincareProduct_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SkinType>): Array<SkinType> {
    return value.map((x)=>from_candid_SkinType_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IngredientAnalysisResult>): Array<IngredientAnalysisResult> {
    return value.map((x)=>from_candid_IngredientAnalysisResult_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HighlightedIngredient>): Array<HighlightedIngredient> {
    return value.map((x)=>from_candid_HighlightedIngredient_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IngredientInfo>): Array<IngredientInfo> {
    return value.map((x)=>from_candid_IngredientInfo_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SkinTypeData>): Array<SkinTypeData> {
    return value.map((x)=>from_candid_SkinTypeData_n51(_uploadFile, _downloadFile, x));
}
function to_candid_ConcernLevel_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConcernLevel): _ConcernLevel {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_IngredientAnalysisResult_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IngredientAnalysisResult): _IngredientAnalysisResult {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_IngredientSafety_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IngredientSafety): _IngredientSafety {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_PriceRange_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceRange): _PriceRange {
    return to_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCategory_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid_SkinConcerns_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkinConcerns): _SkinConcerns {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_SkinTypeData_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkinTypeData): _SkinTypeData {
    return to_candid_record_n66(_uploadFile, _downloadFile, value);
}
function to_candid_SkinType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkinType): _SkinType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_SkincareProduct_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkincareProduct): _SkincareProduct {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isCompatible: boolean;
    safetyClassification: IngredientSafety;
    explanation: string;
    ingredientName: string;
    concernWarnings: boolean;
}): {
    isCompatible: boolean;
    safetyClassification: _IngredientSafety;
    explanation: string;
    ingredientName: string;
    concernWarnings: boolean;
} {
    return {
        isCompatible: value.isCompatible,
        safetyClassification: to_candid_IngredientSafety_n13(_uploadFile, _downloadFile, value.safetyClassification),
        explanation: value.explanation,
        ingredientName: value.ingredientName,
        concernWarnings: value.concernWarnings
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aging: ConcernLevel;
    acne: ConcernLevel;
    concerns: Array<string>;
    pigmentation: ConcernLevel;
    dryness: ConcernLevel;
}): {
    aging: _ConcernLevel;
    acne: _ConcernLevel;
    concerns: Array<string>;
    pigmentation: _ConcernLevel;
    dryness: _ConcernLevel;
} {
    return {
        aging: to_candid_ConcernLevel_n31(_uploadFile, _downloadFile, value.aging),
        acne: to_candid_ConcernLevel_n31(_uploadFile, _downloadFile, value.acne),
        concerns: value.concerns,
        pigmentation: to_candid_ConcernLevel_n31(_uploadFile, _downloadFile, value.pigmentation),
        dryness: to_candid_ConcernLevel_n31(_uploadFile, _downloadFile, value.dryness)
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    suitableSkinTypes: Array<SkinType>;
    name: string;
    description: string;
    concerns: Array<string>;
    priceRange: PriceRange;
    category: ProductCategory;
    brand: string;
    keyIngredients: Array<string>;
}): {
    suitableSkinTypes: Array<_SkinType>;
    name: string;
    description: string;
    concerns: Array<string>;
    priceRange: _PriceRange;
    category: _ProductCategory;
    brand: string;
    keyIngredients: Array<string>;
} {
    return {
        suitableSkinTypes: to_candid_vec_n60(_uploadFile, _downloadFile, value.suitableSkinTypes),
        name: value.name,
        description: value.description,
        concerns: value.concerns,
        priceRange: to_candid_PriceRange_n61(_uploadFile, _downloadFile, value.priceRange),
        category: to_candid_ProductCategory_n63(_uploadFile, _downloadFile, value.category),
        brand: value.brand,
        keyIngredients: value.keyIngredients
    };
}
function to_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    answers: Array<bigint>;
    concerns: SkinConcerns;
    timestamp: bigint;
    detectedSkinType: SkinType;
}): {
    answers: Array<bigint>;
    concerns: _SkinConcerns;
    timestamp: bigint;
    detectedSkinType: _SkinType;
} {
    return {
        answers: value.answers,
        concerns: to_candid_SkinConcerns_n29(_uploadFile, _downloadFile, value.concerns),
        timestamp: value.timestamp,
        detectedSkinType: to_candid_SkinType_n1(_uploadFile, _downloadFile, value.detectedSkinType)
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IngredientSafety): {
    safe: null;
} | {
    conditional: null;
} | {
    harmful: null;
} | {
    risky: null;
} {
    return value == IngredientSafety.safe ? {
        safe: null
    } : value == IngredientSafety.conditional ? {
        conditional: null
    } : value == IngredientSafety.harmful ? {
        harmful: null
    } : value == IngredientSafety.risky ? {
        risky: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkinType): {
    dry: null;
} | {
    combination: null;
} | {
    normal: null;
} | {
    oily: null;
} | {
    sensitive: null;
} {
    return value == SkinType.dry ? {
        dry: null
    } : value == SkinType.combination ? {
        combination: null
    } : value == SkinType.normal ? {
        normal: null
    } : value == SkinType.oily ? {
        oily: null
    } : value == SkinType.sensitive ? {
        sensitive: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConcernLevel): {
    low: null;
} | {
    high: null;
} | {
    none: null;
} | {
    medium: null;
} {
    return value == ConcernLevel.low ? {
        low: null
    } : value == ConcernLevel.high ? {
        high: null
    } : value == ConcernLevel.none ? {
        none: null
    } : value == ConcernLevel.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceRange): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == PriceRange.low ? {
        low: null
    } : value == PriceRange.high ? {
        high: null
    } : value == PriceRange.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): {
    sunscreen: null;
} | {
    cleanser: null;
} | {
    treatment: null;
} | {
    serum: null;
} | {
    moisturizer: null;
} {
    return value == ProductCategory.sunscreen ? {
        sunscreen: null
    } : value == ProductCategory.cleanser ? {
        cleanser: null
    } : value == ProductCategory.treatment ? {
        treatment: null
    } : value == ProductCategory.serum ? {
        serum: null
    } : value == ProductCategory.moisturizer ? {
        moisturizer: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<IngredientAnalysisResult>): Array<_IngredientAnalysisResult> {
    return value.map((x)=>to_candid_IngredientAnalysisResult_n11(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SkinType>): Array<_SkinType> {
    return value.map((x)=>to_candid_SkinType_n1(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SkincareProduct>): Array<_SkincareProduct> {
    return value.map((x)=>to_candid_SkincareProduct_n58(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
